### Get all workouts
GET http://localhost:3000/workouts

### Get a workout by ID (I will replace this with a real ID from our DB later)
GET http://localhost:3000/workouts/6981e95c73af57404816926e

### Create a new workout
POST http://localhost:3000/workouts
Content-Type: application/json

{
  "userId": "Douglas123",
  "type": "strength",
  "durationMin": 90,
  "exercises": [
    {
      "name": "Bench Press",
      "sets": 3,
      "reps": 10,
      "weight": 135
    }
  ],
  "notes": "Feeling strong today like never before!"
}


### Update a workout (Replace ID with a real one from your GET)
PUT http://localhost:3000/workouts/6981e95c73af57404816926d
Content-Type: application/json

{
  "durationMin": 150,
  "notes": "Updated: Feeling strong today like never before!"
}

### Delete a workout
DELETE http://localhost:3000/workouts/6981e927ac34538eca5f828a

### GET all habits (PUBLIC)
GET http://localhost:3000/habits

### GET habit by id (PUBLIC)
GET http://localhost:3000/habits/65b8f2e6a1c9a3e8d1234567

### Create habit 
POST http://localhost:3000/habits

{
  "userName": "test-user-123",
  "name": "Drink water",
  "frequency": "daily",
  "targetCount": 8,
  "category": "health",
  "active": true
}

### Update habit
PUT http://localhost:3000/habits/65b8f2e6a1c9a3e8d1234567

{
  "name": "Drink more water",
  "frequency": "daily",
  "targetCount": 10,
  "category": "health",
  "active": true
}

### Delete habit
DELETE http://localhost:3000/habits/65b8f2e6a1c9a3e8d1234567


